name: Publish Maple to GitHub Packages

on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  push:
    branches:
      - 'Rebrand'       # Run the workflow when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Bump version
      uses: SiqiLu/dotnet-bump-version@master
      with:
        # Version files to bump version. 
        # You can use Glob pattern string (like "**/*.csproj") or Glob patterns array json string (like "["**/*.csproj", "v1.version", "**/*.version.json", "!v2.version.json"]"). # # Patterns supported by Globby are supported. Leading ! changes the meaning of an include pattern to exclude.
        # default: "**/*.csproj"
        # required: false
        version_file: "**/*.csproj"
        
        # Control which part of the version to be bumped. 
        # Example:
        #   "1.0.0.0": Bump the major part of the version.  2.3.4.5 => 3.0.0.0
        #   "0.1.0.0": Bump the minor part of the version.  2.3.4.5 => 2.4.0.0
        #   "0.0.1.0": Bump the patch part of the version.  2.3.4.5 => 2.3.5.0
        #   "0.0.0.1": Bump the minor part of the version.  2.3.4.5 => 2.3.4.6
        #   "1.0.1.0": Bump the major and the patch part of the version.  2.3.4.5 => 3.0.5.0
        #   "1.1.1.1": Bump all the parts of the version.  2.3.4.5 => 3.4.5.6 
        # default: "0.0.1.0"
        # required: false
        version_mask: "0.0.0.1"

        # Overwrite the bumped version. Use this input option to overwrite the version or part of the version. 
        # If you want to modified all versions in the version files to a specifed version number, you should use this input option. 
        # If you do not want overwrite the version or any part of the version, you should just ignore this input option. 
        # Example:
        #   "*.*.*.*" does not overwrite ant part of the version.
        #   "1.*.*.*" overwrite the major part with number 1.
        #   "*.*.*.Alpha" overwrite the build part with string "Alpha".
        #   "*.*.*.${{ github.run_number }}" overwrite the build part with ${{ github.run_number }}.'
        # default: "*.*.*.*"
        # required: false
        version_overwrite: "*.*.*.*"

        # The github token to push changes. Leave the github_token option as default or empty string, the action will not push any changes to your repository.
        # required: false
        github_token: ${{ secrets.TOKEN }}
    - name: Build
      run: dotnet build Maple -c Release
    - name: Pack nugets
      run: dotnet pack Maple -c Release --no-build --output --version-prefix .
    - name: Push to NuGet
      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.TOKEN}} --source https://nuget.pkg.github.com/SamShiels/index.json