name: Publish Maple to GitHub Packages

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build Maple/Maple.csproj -c Release /p:Version=${{ github.event.release.tag_name }}
    - name: Pack nugets
      run: dotnet pack Maple -c Release --no-build --output .
    - name: Push to NuGet
      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.TOKEN}} --source https://nuget.pkg.github.com/SamShiels/index.json